version: "3.5"
services:
  nuxt:
    build: ./app/
    container_name: nuxt
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"
    depends_on:
      - mongo
  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt
  mongo:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db:z
    container_name: mongodb
    ports:
      - "27017:27017"
